In [4]:
import numpy as np

Write a function so that the columns of the output matrix are powers of the input
vector.

In [6]:
import numpy as np

def myvander(x,n,b):
    if b>0:
        return np.column_stack(x**(n-i-1) for i in range(n-1,-1,-1))
    else:
        return np.column_stack(x**(n-i-1) for i in range(n))
      
input_matrix=np.array((1,2,3,4,5))
n=5

print("MyVander called with function parameter as increasing order - ")
print(myvander(input_matrix,n,True))

print("MyVander called with function parameter as decreasing order - ")
print(myvander(input_matrix,n,False))


MyVander called with function parameter as increasing order - 
[[  1   1   1   1   1]
 [  1   2   4   8  16]
 [  1   3   9  27  81]
 [  1   4  16  64 256]
 [  1   5  25 125 625]]
MyVander called with function parameter as decreasing order - 
[[  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]
 [625 125  25   5   1]]


In [7]:
np.vander(input_matrix,5,increasing=True)

array([[  1,   1,   1,   1,   1],
       [  1,   2,   4,   8,  16],
       [  1,   3,   9,  27,  81],
       [  1,   4,  16,  64, 256],
       [  1,   5,  25, 125, 625]])

In [10]:
np.vander(input_matrix,5,increasing=False)

array([[  1,   1,   1,   1,   1],
       [ 16,   8,   4,   2,   1],
       [ 81,  27,   9,   3,   1],
       [256,  64,  16,   4,   1],
       [625, 125,  25,   5,   1]])

Write a function to find moving average in an array over a window:
Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [2]:
def mv(a,k):
    l=[]
    i=0
    while i < len(a)-k+1:
        l.append(sum(a[i:i+k])/k)
        i=i+1
    return l  

numbers = [10, 20, 30, 40, 50, 60, 70, 80, 90 ,100]
k = 3

print (mv(numbers,k))

  

    

[20.0, 30.0, 40.0, 50.0, 60.0, 70.0, 80.0, 90.0]


In [5]:
def moving_average(data_set, periods=3):
    weights = np.ones(periods) / periods
    return np.convolve(data_set, weights, mode='valid')
print(moving_average(numbers,k))

[20. 30. 40. 50. 60. 70. 80. 90.]
