In [51]:
def div():
    try:
        x=int(input('Enter Numerator:'))
        y=int(input('Enter Denominator: '))
        return x/y
    except ZeroDivisionError:
        print('Divided by ZERO Error: Denominator passed to div function cannot be ZERO')
    except:
        print('Error: Please enter valid number input for division operation')
    
print(div())


Enter Numerator:2
Enter Denominator: 0
Divided by ZERO Error: Denominator passed to div function cannot be ZERO
None


In [52]:
from itertools import product
subjects=["Americans","Indians"]
verbs=["play","watch"]
objects=["Baseball",'Cricket']

#for i in subjects:
#    for j in verbs:
#        for k in objects:
#            print(i+' '+j+' '+k +'.')

#x=[print(i+' '+j+' '+k +'.') for i in subjects for j in verbs for k in objects]

for i in product(subjects,verbs,objects):
    print (i[0]+' '+i[1]+' '+i[2]+'.')


Americans play Baseball.
Americans play Cricket.
Americans watch Baseball.
Americans watch Cricket.
Indians play Baseball.
Indians play Cricket.
Indians watch Baseball.
Indians watch Cricket.


In [53]:
import numpy as np

def myvander(x,n,b):
    if b>0:
        return np.column_stack(input_matrix**(n-i-1) for i in range(n-1,-1,-1))
    else:
        return np.column_stack(input_matrix**(n-i-1) for i in range(n))
      
input_matrix=np.array((1,2,3,4,5))
n=5

print("MyVander called with function parameter as increasing order - ")
print(myvander(input_matrix,n,True))

print("MyVander called with function parameter as decreasing order - ")
print(myvander(input_matrix,n,False))





MyVander called with function parameter as increasing order - 
[[  1   1   1   1   1]
 [  1   2   4   8  16]
 [  1   3   9  27  81]
 [  1   4  16  64 256]
 [  1   5  25 125 625]]
MyVander called with function parameter as decreasing order - 
[[  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]
 [625 125  25   5   1]]
